### PR TITLE
31 Added new strings to fi.json 

### PR DESCRIPTION
**Pull request by Aappo**
En tiedä miksi viimeinen kaksoispiste on punaisella taustalla.
I mean I don't know why the last colon has a red background.

### CODE REVIEW

**Comment by pirttpi1** [comment]
I think the row before,  ',' is missing

**Comment by Aappo** [comment]
Thanks Pia, I added the comma now.

**Comment by Aappo** [comment]
Vaihdoin line id:n line numberiksi niin kuin paliksessa tuumittiin.

**Comment by Aappo** [comment]
Numerot lyhennetty.

**Pull request merged**
